import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import { ThemeProvider } from "next-themes"
import ThemeSwitcher from "./components/ThemeSwitcher";
import "./globals.css";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >

        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="dark:bg-black">
                <ThemeSwitcher />
              <main className="">
                {children}
              </main>
            </div>
          </ThemeProvider>
      </body>
    </html>
  );
}
